export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
export const FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCESS";
export const FETCH_USER_DETAILS_FAILURE = "FETCH_USER_DETAILS_FAILURE";

export const GET_PART_USER = "GET_PART_USER";
export const EDIT_DETAILS = "EDIT_DETAILS";
export const DELETE_DETAILS = "DELETE_DETAILS";
export const COMMENT_DETAILS = "COMMENT_DETAILS";
export const ADD_POST = "ADD_POST";
export const ADD_POST_ERROR = "ADD_POST_ERROR";
